BUILD_DATE := $(shell date +%Y%m%d)
BUILD_TIME := $(shell date +%H%M)
# Versioning System
# Use signing keys for only official
ifndef AWAKEN_BUILD_TYPE
    AWAKEN_BUILD_TYPE := UNOFFICIAL
endif

# Set all versions
AWAKEN_BASE_VERSION := 1.0
AWAKEN_PLATFORM_VERSION := 11
AWAKEN_VERSION := $(TARGET_PRODUCT)-$(BUILD_DATE)-$(BUILD_TIME)-$(AWAKEN_PLATFORM_VERSION)-$(AWAKEN_BASE_VERSION)-$(AWAKEN_BUILD_TYPE)
ROM_FINGERPRINT := Awaken/$(PLATFORM_VERSION)/$(AWAKEN_BUILD_TYPE)/$(BUILD_DATE)$(BUILD_TIME)

# Declare it's a Awaken build
AWAKEN_BUILD := true
